### ISSUE TITLE
Nginx cannot start for active akamai-g2o-nginx-wrapper.lua

### ISSUE THREAD

**Issue by lvthao** [lukaszczerpak/akamai-g2o-lua#2]
Hello, 
I follow all the procedure to install on nginx and i got this issue  when i active the init_by_lua 'require("/etc/nginx/akamai-g2o-nginx-wrapper")'; 
I install luaossl 20181207-0 (installed) . LuaRocks 2.3.0 version.
Here is the log as there is no _openssl under '/usr/local/share/lua/5.1/
<<
     : no field package.preload['_openssl.hmac']
     : no file '/etc/ /_openssl/hmac.lua'
     : no file './_openssl/hmac.lua'
     : no file '/usr/share/ -luajit-2.1/_openssl/hmac.lua'
     : no file '/usr/local/share/lua/5.1/_openssl/hmac.lua'
     : no file '/usr/local/share/lua/5.1/_openssl/hmac/init.lua'
     : no file '/usr/share/lua/5.1/_openssl/hmac.lua'
     : no file '/usr/share/lua/5.1/_openssl/hmac/init.lua'
     : no file './_openssl/hmac.so'
     : no file '/usr/local/lib/lua/5.1/_openssl/hmac.so'
     : no file '/usr/lib/lua/5.1/_openssl/hmac.so'
     : no file '/usr/local/lib/lua/5.1/loadall.so'
     : no file './_openssl.so'
     : no file '/usr/local/lib/lua/5.1/_openssl.so'
     : no file '/usr/lib/lua/5.1/_openssl.so'
     : no file '/usr/local/lib/lua/5.1/loadall.so'
     : stack traceback:
     : [C]: in function 'require'
     : /usr/share/lua/5.1/openssl/hmac.lua:1: in main chunk
     : [C]: in function 'require'
     : /etc/ /akamai-g2o.lua:1: in main chunk
     : [C]: in function 'require'
     : .//etc/ /akamai-g2o- -wrapper.lua:2: in main chunk
     : [C]: in function 'require'
     : init_by_lua:1: in main chunk
>>
Could you help to check ?

**Comment by lukaszczerpak** [comment]
Hi,

What OS do you use? Is nginx installed from the OS or external repository? Can you double check if nginx is using lua 5.1 from your OS or maybe there are two versions of lua installed?

**Comment by lvthao** [comment]
i'm using nginx plus and install follow this document (https://docs.nginx.com/nginx/admin-guide/dynamic-modules/lua/). i'm install on centos 7.

**Comment by lukaszczerpak** [comment]
Thanks! I will look into that and get back to you.

**Comment by lukaszczerpak** [comment]
I was able to reproduce it - used the following steps to setup the environment:

Install nginx + lua:

```
wget -P /etc/yum.repos.d https://cs.nginx.com/static/files/nginx-plus-7.4.repo
yum install -y nginx-plus
yum install -y nginx-plus-module-lua
```

then luarocks and luaossl:

```
yum -y update
yum install -y epel-release
yum update -y
# yum groupinstall -y  "Development Tools"
yum install -y luarocks openssl-devel lua-devel gcc
luarocks install luaossl
```

After that I downloaded g2o wrapped and library to `/etc/nginx/lua`:

```
mkdir /etc/nginx/lua
wget -P /etc/nginx/lua https://raw.githubusercontent.com/lukaszczerpak/akamai-g2o-lua/master/akamai-g2o-nginx-wrapper.lua
wget -P /etc/nginx/lua https://raw.githubusercontent.com/lukaszczerpak/akamai-g2o-lua/master/akamai-g2o.lua
```

As a result I got the same error due to missing luaossl dependency. Apparently nginx-plus uses LuaJIT which doesn't know about lua extensions installed on the system. The following fixed the problem:

1) Initialize g2o wrapper in `nginx.conf` file in `http {}` section:

```
http {
    ...

    include /etc/nginx/conf.d/*.conf;

    lua_package_cpath "/usr/lib64/lua/5.1/?.so;;";
    lua_package_path "/usr/share/lua/5.1/?.lua;/etc/nginx/lua/?.lua;;";
    init_by_lua_block { require "akamai-g2o-nginx-wrapper" }
}
```

Then in vhost configuration I was able to use the verification successfully:

```
location / {
    access_by_lua_block { akamai_g2o_validate_nginx(5, "s3cr3tK3y", 30) }
    root   /usr/share/nginx/html;
    index  index.html index.htm;
}
```

Let me know it solves the problem on your side as well. Otherwise I will investigate further.
**Please note I updated the wrapper so pull the latest version from the repo.**

**Comment by lvthao** [comment]
Hi lukaszczerpak, 
The nginx is loading and we are process some test on that.
I want to allow some IP which can connect directly without G20 and the other will need G20. I tested with some config below but i got access forbiden 403. We didn't have any index file on our documet root.
location / {
                if ($remote_addr = "myIP") {
                        set $allow true;
                 }
                if ($allow = false) {
                         access_by_lua 'akamai_g2o_validate_nginx(5, "xxx", 30)';
                }
                try_files $uri /app.php$is_args$args;
}
      location ~ \.php(/|$) {
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                include             common/fastcgi_params;
                fastcgi_read_timeout 120;
                fastcgi_pass        unix:/var/run/fpm-tip.socket;
                fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                fastcgi_param DOCUMENT_ROOT ....;
                internal;

Could you help if possible?

**Comment by lvthao** [comment]
Hi, 
I able  to fix this issue to allow some IP connection withou G2o. 
Thank you
